Fix musl compilation error related to LFS64
LFS64 interfaces are deprecated in musl, since they are not needed
there. See notes for musl-1.2.4.tar.gz in
https://musl.libc.org/releases.html and also
https://wiki.gentoo.org/wiki/Musl_porting_notes#error:_LFS64_interfaces_.28.2A64_undeclared_here.2C_ex._pread64.29